### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by tilllt** [ravensorb/traefik-certificate-exporter#1]
I would like to use your tool AS a docker Container, but there is a permission Problem:

traefik-certificate-exporter-1  | 2024-07-10 07:32:04,741 - INFO - Certificates changed found in file: /data/acme.json
traefik-certificate-exporter-1  | 2024-07-10 07:32:06,741 - DEBUG - [DEBUG] SStarting the work
traefik-certificate-exporter-1  | 2024-07-10 07:32:06,741 - INFO - Processing file: /data/acme.json
traefik-certificate-exporter-1  | 2024-07-10 07:32:06,741 - ERROR - Error processing file '/data/acme.json': [Errno 13] Permission denied: '/data/acme.json'

The thing is, when i start a bash inside the Container and do ˋ/cat/data/acme.jsonˋ it properly outputs the File. Could it be that you are trying to Open acme.json with RW permissions?

p.s. your Code is full of spelling mistakes, which generally i absolutely dont care about, but this is an example from the sample config your tool creates, where its unclear If rosolverInPathName is Just wrong in the sample, or If your tool expects the setting to have this spelling...

fileSpec": "*.json",
    "outputPath": "./certs",
    "traefikResolverId": "",
    "rosolverInPathName": false,
    "flat": false,

**Comment by ravensorb** [comment]
It is possible you might be running a bit of an older version.  Have you had a chance to look at the latest v0.1.2 or v0.1.3?  Also due to how traefik works, when you run this exporter you will need to run it as root (either locally or within docker).

BTW -- thanks for the notes on the spelling issues.

**Comment by tilllt** [comment]
Hey, I am using your docker image

image: ravensorb/traefik-certificate-exporter:latest

I was assuming that's built by a CI/CD Action?

**Comment by ravensorb** [comment]
Are you running the container as root?

**Comment by tilllt** [comment]
Yes

**Comment by tilllt** [comment]
p.s. I tried using the python version directly and it works fine. So it seems to be a docker problem. maybe the error 13 is not a read error but a write error for the output files?

**Comment by ravensorb** [comment]
Can you provide enough details for me to try to replicate the issue?  
* Full compose for both this container and traefik
* any .env files related to both of them

**Comment by tilllt** [comment]
Hey sorry for the delay, did you change something? Because I did a fresh pull - there was indeed a new image - and the export (using the docker container version) worked now!

The only issue I could see now is that it ignored the "INCLUDE_DOMAINS" setting from the env variables in the docker-compose.yml but exported all certs. Which is not really a problem for me.

**Comment by ravensorb** [comment]
@tilllt -- thanks for the info on the env issue.  I'll take a look.  And glad it is working now!  v0.1.3 was a bit of a rewrite to make it easier to work with going forward.
